### ISSUE TITLE
Error in stage 11

### ISSUE THREAD

**Issue by han-xie** [nwpuaslp/kws_mia#1]
Hi, there,
I'm trying to reproduce your results but got blocked in stage 11.

## Following is the output log of run_kws.sh:
steps/nnet3/get_egs_targets.sh: feature type is raw
steps/nnet3/get_egs_targets.sh: working out number of frames of training data
steps/nnet3/get_egs_targets.sh: working out feature dim
steps/nnet3/get_egs_targets.sh: creating 63 archives, each with 399689 egs, with
steps/nnet3/get_egs_targets.sh:   8 labels per example, and (left,right) context = (16,12)
steps/nnet3/get_egs_targets.sh: Getting validation and training subset examples.
>  bash: line 1: 16136 Aborted                 (core dumped) ( nnet3-get-egs ......)

## And the ASSERTION FAILURE in create_valid_subset.log is:
nnet3-get-egs --num-pdfs=10 --frame-subsampling-factor=1 --length-tolerance=2 --left-context=16 --right-context=12 --compress=true --num-frames=8 'ark,s,cs:utils/filter_scp.pl exp/nnet3/tdnn_test_kws/egs/valid_uttlist data/fbank/train/feats.scp | apply-cmvn --norm-means=false --norm-vars=false --utt2spk=ark:data/fbank/train/utt2spk scp:data/fbank/train/cmvn.scp scp:- ark:- |' 'ark,s,cs:utils/filter_scp.pl exp/nnet3/tdnn_test_kws/egs/valid_uttlist exp/kws_ali_test/ali.scp | ali-to-post scp:- ark:- |' ark:exp/nnet3/tdnn_test_kws/egs/valid_all.egs
......
WARNING (nnet3-get-egs[5.5.3-d6f5]:main():nnet3-get-egs.cc:234) No pdf-level posterior for key BAC009S0100W0128
> ASSERTION_FAILED (nnet3-get-egs[5.5.3-d6f5]:SparseVector():sparse-matrix.cc:266) Assertion failed: (pairs_.front().first >= 0 && pairs_.back().first < dim_)

## Question
1. Can you help to test whether the one-stop script ```run_kws.sh``` works fine for you?
2. Do you remember doing any other steps which you forgot to add to run_kws.sh?
3. If the script works fine for you, I guess it's due to an issue of different Kaldi version, which version do you use?

I will appreciate it so much if you can give me a quick response.

**Comment by nwpuaslp** [comment]
Thanks for your question. I will check my code soon and answer you if I find what wrong is happening!

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: Han Xie<mailto:notifications@github.com>
发送时间: 2020年2月12日 10:19
收件人: nwpuaslp/kws_mia<mailto:kws_mia@noreply.github.com>
抄送: Subscribed<mailto:subscribed@noreply.github.com>
主题: [nwpuaslp/kws_mia] Error in stage 11 (#1)


Hi, there,
I'm trying to reproduce your results but got blocked in stage 11.

Following is the output log of run_kws.sh:

steps/nnet3/get_egs_targets.sh: feature type is raw
steps/nnet3/get_egs_targets.sh: working out number of frames of training data
steps/nnet3/get_egs_targets.sh: working out feature dim
steps/nnet3/get_egs_targets.sh: creating 63 archives, each with 399689 egs, with
steps/nnet3/get_egs_targets.sh: 8 labels per example, and (left,right) context = (16,12)
steps/nnet3/get_egs_targets.sh: Getting validation and training subset examples.

bash: line 1: 16136 Aborted (core dumped) ( nnet3-get-egs ......)

And the ASSERTION FAILURE in create_valid_subset.log is:

nnet3-get-egs --num-pdfs=10 --frame-subsampling-factor=1 --length-tolerance=2 --left-context=16 --right-context=12 --compress=true --num-frames=8 'ark,s,cs:utils/filter_scp.pl exp/nnet3/tdnn_test_kws/egs/valid_uttlist data/fbank/train/feats.scp | apply-cmvn --norm-means=false --norm-vars=false --utt2spk=ark:data/fbank/train/utt2spk scp:data/fbank/train/cmvn.scp scp:- ark:- |' 'ark,s,cs:utils/filter_scp.pl exp/nnet3/tdnn_test_kws/egs/valid_uttlist exp/kws_ali_test/ali.scp | ali-to-post scp:- ark:- |' ark:exp/nnet3/tdnn_test_kws/egs/valid_all.egs
......
WARNING (nnet3-get-egs[5.5.3-d6f5]:main():nnet3-get-egs.cc:234) No pdf-level posterior for key BAC009S0100W0128

ASSERTION_FAILED (nnet3-get-egs[5.5.3-d6f5]:SparseVector():sparse-matrix.cc:266) Assertion failed: (pairs_.front().first >= 0 && pairs_.back().first < dim_)

Question

  1.  Can you help to test whether the one-stop script run_kws.sh works fine for you?
  2.  Do you remember doing any other steps which you forgot to add to run_kws.sh?
  3.  If the script works fine for you, I guess it's due to an issue of different Kaldi version, which version do you use?

I will appreciate it so much if you can give me a quick response.

―

**Comment by han-xie** [comment]
I have solved this problem and submitted a PR, you can merge it into master branch.

Thanks for sharing your scripts.
